import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Image from "next/image";
import { cn } from "@/lib/utils";
import background from "@/public/background.jpg";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(GeistSans.className, "relative min-h-screen h-full")}>
        <div className="fixed inset-0 -z-10">
          <Image
            src={background}
            alt="background"
            fill
            priority
            placeholder="blur"
            className="object-cover"
          />
          <div className="absolute inset-0 bg-black/20" />
        </div>
        {children}
      </body>
    </html>
  );
}
